version: "3.8"
services:
  mysql_alias:
    image: 'mysql:latest'
    restart: always
    volumes:
      - ./mysql/init/mysql_config.sql:/docker-entrypoint-initdb.d/mysql_config.sql
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=0000
  server:
    build: .
    restart: always
    volumes:
      - ./DB:/DB
      - ./Server:/Server
    ports:
      - 8080:8080
    depends_on:
      - mysql_alias
